@HOST=http://localhost:50000

### ========== GET Random Joke =================================================
GET {{HOST}}/api/jokes/random/


### ========== GET Category Joke ===============================================
GET {{HOST}}/api/jokes/category/{category}/


### ========== GET Filter Jokes ================================================
GET {{HOST}}/api/jokes/filter?search=TESTEtesteTESTE&limit=10