# Generated by Django 3.2.9 on 2022-06-24 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['email'], name='jokes_subsc_email_e2ff56_idx'),
        ),
    ]
